# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Anis Oueslati
tagline:          'A Jekyll theme'
description:      'PhD student at King s Abdallah University of Science and Technology in Computer Science in PRADA Lab'
url:              https://oueslaa.github.io/
baseurl:          /

author:
  name:           'Anis Oueslati'
  url:            https://www.linkedin.com/in/anis-oueslati/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
